version: '3'
services:
  nginx:
    image: lscr.io/linuxserver/nginx:1.24.0
    container_name: lempstack_nginx
    ports:
      - 80:80
      # - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    env_file:
      - ./secure/.env
    volumes:
      - ./config/nginx:/config
      - ./secure:/config/secure
      - ./nginx-default.conf:/config/nginx/site-confs/default.conf
      - ./app:/config/www
  mariadb:
    image: lscr.io/linuxserver/mariadb:10.11.5
    container_name: lempstack_mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    env_file:
      - ./secure/.env
    volumes:
      - ./config/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:5.2.1
    container_name: lempstack_phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - PMA_ARBITRARY=1
    env_file:
      - ./secure/.env
    volumes:
      - ./config/phpmyadmin:/config
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - mariadb
